apiRules:
- include:
    uidRegex: ^nickmaltbie\.MinimapTools
    type: Namespace
- include:
    uidRegex: ^nickmaltbie\.MinimapTools\.*
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace